figure(1)
subplot(1,2,1)
plot(linspace(0,time_step*dt,time_step),x_dyn)
ylabel('x_dyn')
xlabel('time')
title('without_fl')

figure(2)
subplot(1,2,1)
plot(linspace(0,time_step*dt,time_step),y_dyn)
ylabel('y_dyn')
xlabel('time')
title('without_fl')

figure(3)
subplot(1,2,1)
plot(linspace(0,time_step*dt,time_step),Fx)
ylabel('Fx')
xlabel('time')
title('without_fl')

figure(4)
subplot(1,2,1)
plot(linspace(0,time_step*dt,time_step),Fy)
ylabel('Fy')
xlabel('time')
title('without_fl')

figure(5)
subplot(1,2,1)
plot(linspace(0,time_step*dt,time_step),s_fl[0]+s_fl[1])
ylabel('S_fl')
xlabel('time')
title('without_fl')